include:
  - project: 'Infrastructure/openshift-images/ci-templates'
    file: '/kaniko.yml'

odrs-dev:
  extends:
    - .kaniko-root
  variables:
    CI_PROJECT_NAME: "odrs"
    OCI_TAG: "dev"

odrs:
  extends:
    - .kaniko-root
  variables:
    OCI_TAG: "latest"
  when: manual
