include:
  - project: 'Infrastructure/openshift-images/ci-templates'
    file: '/kaniko.yml'

odrs-dev:
  extends:
    - .kaniko-root
  variables:
    CI_CUSTOM_IMAGE_NAME: "odrs"
    OCI_TAG: "dev"

odrs:
  extends:
    - .kaniko-root
  variables:
    CI_CUSTOM_IMAGE_NAME: "odrs"
    OCI_TAG: "latest"
  when: manual

nginx:
  extends:
    - .kaniko-root
  variables:
    CI_CUSTOM_IMAGE_NAME: "odrs"
    OCI_TAG: "nginx"
    DOCKERFILE: "Dockerfile.nginx"
  when: manual
