#!/bin/bash
set -euo pipefail

export FLASK_APP=odrs/__init__.py 
export SQLALCHEMY_TRACK_MODIFICATIONS=False
flask db upgrade

while true; do python3 /opt/app-root/src/cron.py fsck ; sleep 43200 ; done &

curl https://dl.flathub.org/repo/appstream/x86_64/appstream.xml.gz -o /tmp/appstream.xml.gz
python /opt/app-root/src/cron.py appstream-import /tmp/appstream.xml.gz

curl https://raw.githubusercontent.com/hughsie/badwords/master/badwords.csv -o /tmp/badwords.csv
python /opt/app-root/src/cron.py taboo-import /tmp/badwords.csv

while true; do
  python /opt/app-root/src/cron.py ratings /opt/app-root/src/odrs/static/ratings.json
  cp /opt/app-root/src/odrs/static/ratings.json /opt/app-root/src/odrs/static/ratings.json.bak
  gzip /opt/app-root/src/odrs/static/ratings.json
  mv /opt/app-root/src/odrs/static/ratings.json.bak /opt/app-root/src/odrs/static/ratings.json
  brotli -k /opt/app-root/src/odrs/static/ratings.json
  sleep 43200
done &

exec /usr/libexec/s2i/run
